spring.application.name=pos

spring.datasource.url=jdbc:mysql://localhost:3306/pos
spring.datasource.username=root
spring.datasource.password=root

# Server
server.port=8080

# JDBC
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.main.allow-bean-definition-overriding=true